version: "2"
services:
  web:
    build: "./web"
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    restart: "always"
    build: "./db"
    ports:
      - "6000:5432"
  music:
    build: "./music"
    ports: 
      - "8081:8081"
  prompts:
    build: "./prompts"
    ports:
      - "8082:8082"
  sprites: 
    build: "./sprites"
    ports: 
      - "8083:8083"
  worlds: 
    build: "./worlds"
    ports: 
      - "8084:8084"