version: "2"
services:
  web:
    image: "174580102496.dkr.ecr.us-east-1.amazonaws.com/magic-box:web"
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      - PROD=true
      - PORT=80
      - PGHOST=0.0.0.0
    expose: 
      - "80"
    logging:
      driver: awslogs
      options: 
        awslogs-group: magic-box
        awslogs-region: us-east-1
        awslogs-stream-prefix: magic-box
  db:
    restart: "always"
    image: "174580102496.dkr.ecr.us-east-1.amazonaws.com/magic-box:db"
    ports:
      - "5432:5432"
    logging:
      driver: awslogs
      options: 
        awslogs-group: magic-box
        awslogs-region: us-east-1
        awslogs-stream-prefix: magic-box
  music:
    image: "174580102496.dkr.ecr.us-east-1.amazonaws.com/magic-box:music"
    ports: 
      - "8081:8081"
    logging:
      driver: awslogs
      options: 
        awslogs-group: magic-box
        awslogs-region: us-east-1
        awslogs-stream-prefix: magic-box
  prompts:
    image: "174580102496.dkr.ecr.us-east-1.amazonaws.com/magic-box:prompts"
    ports:
      - "8082:8082"
    logging:
      driver: awslogs
      options: 
        awslogs-group: magic-box
        awslogs-region: us-east-1
        awslogs-stream-prefix: magic-box
  sprites: 
    image: "174580102496.dkr.ecr.us-east-1.amazonaws.com/magic-box:sprites"
    ports: 
      - "8083:8083"
    logging:
      driver: awslogs
      options: 
        awslogs-group: magic-box
        awslogs-region: us-east-1
        awslogs-stream-prefix: magic-box
  worlds: 
    image: "174580102496.dkr.ecr.us-east-1.amazonaws.com/magic-box:worlds" 
    ports: 
      - "8084:8084"
    logging:
      driver: awslogs
      options: 
        awslogs-group: magic-box
        awslogs-region: us-east-1
        awslogs-stream-prefix: magic-box